### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ybayle** [keunwoochoi/magnatagatune-list#2]
Hi, this is a great repo!
Did you consider to contribute to [AI-metrics](https://github.com/AI-metrics/AI-metrics) and or [Awesome](https://github.com/sindresorhus/awesome), for more visibility?

**Comment by keunwoochoi** [comment]
Hi, thanks. No I didn't and don't think I would -- I'm not really following works on MagnaTagATune anymore.

**Comment by ybayle** [comment]
Ok, I'll fork if I need to update.
