### ISSUE TITLE
After a few epochs, the difference between Valid loss and Loss increases.

### ISSUE THREAD

**Issue by sohrabkhanbadr** [keunwoochoi/magnatagatune-list#3]
Hello Dr. Choi,
Please help. How can I solve this problem?
https://stackoverflow.com/questions/70810493/how-to-compile-your-cnn-model-for-multi-classification-problems

**Comment by keunwoochoi** [comment]
hi, sounds like you’re facing overfitting. unfortunately, there’s no single answer to fight against it. i’d study general solutions in ml. perhaps this can be useful to you https://music-classification.github.io/tutorial/landing-page.html .

**Comment by sohrabkhanbadr** [comment]
Thank you very much for your attention and guidance.
